---
- name: Show switches hostname and ios version
  hosts: all
  vars_prompt:
    - name: username
      prompt: "Enter your username"
      private: false # Set to true to hide input (for passwords)

    - name: password
      prompt: "Enter your password"
      private: true # Hides the input as it's typed

  tasks:
    - name: Gather network facts
      ios_facts:
        gather_subset: all
      register: netconfig

    - name: Assign netconfig to var
      set_fact:
        nbrlist: "{{ netconfig.ansible_facts.ansible_net_neighbors | dict2items }}"
        nbrs: "{{ netconfig.ansible_facts.ansible_net_neighbors.values() }}"
        interfaces: "{{ netconfig.ansible_facts.ansible_net_neighbors.keys() }}"

    - name: Get CDP neighbors Raw
      debug:
        msg: "Interface name: {{ item.key }} Neighbor IP: {{ item.value[0].ip }}"
      loop: "{{ nbrlist }}"
